export { heroContent, type HeroContent, type CtaButton } from './hero';
export { contactContent } from './contact';
export { themeConfig, type ThemeConfig } from './theme';
export { professionalMilestones } from './professional-journey';
export { type ProfessionalMilestone } from '@/components/sections/ProfessionalJourney';
export { projectsContent, type Project, type ProjectsContent } from './projects';
export { technicalExpertiseContent, type TechnicalExpertiseContent, type SkillCategory, type TechnicalSkill } from './technical-expertise';
export { footerContent } from './footer';
export { iconConfig, type IconData, type IconConfig } from './icon';
export { blogFiltersContent, type BlogFiltersData } from './blog-filters'; 